// <auto-generated />
namespace EvaluationApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WebsiteDateCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebsiteDateCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202102081302529_WebsiteDateCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
